# Generated by Django 4.2.6 on 2023-10-08 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AppUser",
        ),
    ]
